### ISSUE TITLE
Autocomplete in FactoidEditor does not give enough information to make decisions?

### ISSUE THREAD

**Issue by GVogeler** [acdh-oeaw/apis-instance-manmax#25]
Gendering Maximilian: "Factoid Editor erlaubt nicht zweifelsfrei die Identifikation bereits angelegter Personen; für eine umfassende Suche muss der alte Editor zusätzlich herangezogen werden; Eingaben ohne gleichzeitig möglichen Such-Abgleich sind nicht sinnvoll;"

**Comment by richardhadden** [comment]
By "not enough information", they mean "We need to see all the other factoids involving these persons"?

The schuh index entries especially are pretty well disambiguated (if there's a name, there is normally at least a role or something also mentioned).

It would be useful to change the search logic to split on words and identify all those words, rather than a complete string of text (e.g. typing "Ehefrau Moringer" doesn't find "Ehefrau von Ulrich Moringer" at the moment)

**Comment by GVogeler** [comment]
enhance search in autocomplete would be related to #13

**Comment by GVogeler** [comment]
see #31 31
